[package]
name = "photocraft"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "photocraft"
description = "Photocraft: an open-source, sovereign raster graphics editor powered by Martensite"

[dependencies]
photocraft-engine = { path = "../../crates/engine" }
photocraft-ui-martensite = { path = "../../crates/ui-martensite" }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/photocraft", dest = "/usr/bin/photocraft", mode = "755" }
]

[build-dependencies]
winresource = "0.1"
